# Generated by Django 4.1.4 on 2023-01-11 18:26

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sfaq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ftitle', models.CharField(max_length=150)),
                ('ans', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='stag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('d_time', models.DateTimeField()),
                ('himage', models.ImageField(upload_to='portfoliothumb')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('fdes', froala_editor.fields.FroalaField(max_length=1000)),
                ('ptitle1', models.CharField(max_length=1000)),
                ('pfdes1', froala_editor.fields.FroalaField(max_length=1000)),
                ('ptitle2', models.CharField(max_length=1000)),
                ('pfdes2', froala_editor.fields.FroalaField(max_length=1000)),
                ('ptitle3', models.CharField(max_length=1000)),
                ('pfdes3', froala_editor.fields.FroalaField(max_length=1000)),
                ('ptitle4', models.CharField(max_length=1000)),
                ('pfdes4', froala_editor.fields.FroalaField(max_length=1000)),
                ('mtitle', models.CharField(max_length=1000)),
                ('mimage', models.ImageField(upload_to='portfoliothumb')),
                ('mdes', froala_editor.fields.FroalaField(max_length=1000)),
                ('faqtitle', models.CharField(max_length=1000)),
                ('sfaq', models.ManyToManyField(blank=True, to='services.sfaq')),
                ('tags', models.ManyToManyField(blank=True, to='services.stag')),
            ],
        ),
    ]
