# Generated by Django 4.1.4 on 2023-01-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_d_time_service_mmimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
