# Generated by Django 4.1.4 on 2023-01-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='shortdes',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
