# Generated by Django 4.1.4 on 2023-01-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_shortdes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='tags',
            new_name='tagss',
        ),
    ]
