# Generated by Django 4.1.4 on 2023-01-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_tags_service_tagss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='tagss',
            new_name='tags',
        ),
    ]
