# Generated by Django 4.1.4 on 2023-01-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_rename_tagss_service_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stag',
            new_name='Tag',
        ),
    ]
