# Generated by Django 4.1.4 on 2023-01-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_stag_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='ServiceTag',
        ),
    ]
