# Generated by Django 4.1.4 on 2023-01-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_rename_tag_servicetag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='tags',
            new_name='stags',
        ),
    ]
