# Generated by Django 4.1.4 on 2023-01-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_rename_tags_service_stags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='stags',
            new_name='tags',
        ),
    ]
