# Generated by Django 4.1.4 on 2023-01-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Aimage',
            new_name='authorimage',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Bimage',
            new_name='blogimage',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='BTimage',
            new_name='thumbimage',
        ),
    ]
