# Generated by Django 4.1.4 on 2023-01-05 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_team_detail_addtime'),
        ('blog', '0003_author_remove_blog_authorimage_blog_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='time',
            new_name='addtime',
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.team_detail'),
        ),
    ]
