# Generated by Django 4.1.4 on 2023-01-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_time_blog_addtime_alter_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='addtime',
            new_name='add_time',
        ),
    ]
