# Generated by Django 4.1.4 on 2023-01-05 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_rename_addtime_team_detail_add_time'),
        ('blog', '0007_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about.team_detail'),
        ),
    ]
