# Generated by Django 4.1.4 on 2023-01-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
