# Generated by Django 4.1.4 on 2023-01-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_author_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.SlugField(max_length=100),
        ),
    ]
