# Generated by Django 4.1.4 on 2023-01-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blog_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authorimage',
            new_name='authorImage',
        ),
    ]
