# Generated by Django 4.1.4 on 2023-01-09 18:18

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='des',
            field=froala_editor.fields.FroalaField(max_length=1000),
        ),
    ]
