# Generated by Django 4.1.4 on 2023-01-14 12:59

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_faqs_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('working_time', models.CharField(max_length=100)),
                ('working_day', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('vacancy', models.CharField(max_length=100)),
                ('content', froala_editor.fields.FroalaField(max_length=5000)),
                ('image', models.ImageField(upload_to='career')),
                ('url', models.SlugField(max_length=100)),
            ],
        ),
    ]
