# Generated by Django 4.1.4 on 2023-01-05 16:18

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('content', froala_editor.fields.FroalaField(max_length=1000)),
                ('image', models.ImageField(upload_to='team')),
                ('facebook', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('freelancer', models.CharField(max_length=100)),
                ('upwork', models.CharField(max_length=100)),
                ('url', models.SlugField(max_length=100)),
            ],
        ),
    ]
