# Generated by Django 4.1.4 on 2023-01-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='team_details',
            new_name='team_detail',
        ),
    ]
