# Generated by Django 4.1.4 on 2023-01-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_team_details_team_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_detail',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
