# Generated by Django 4.1.4 on 2023-01-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_team_detail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_detail',
            name='url',
            field=models.SlugField(max_length=100),
        ),
    ]
